add tabindex to coursses
DigitalCareerInstitute/marketing-website pull request #395
Opened 2021-06-13 10:17 UTC by Osman190

2021-06-13 15:25 UTC, spielhoelle commented
I think we should keep also the .keepme tule in the uploads.

2021-06-13 15:51 UTC, spielhoelle requested changes

2021-06-13 15:51 UTC, spielhoelle commented on controllers/UserController.js
> +          // await sendVerificationMail(res, req, userToken);
We need this line

2021-06-13 15:51 UTC, spielhoelle commented on controllers/UserController.js
> +        console.log(err)
I think we don't need that console.log here. But I don't know if we catch that thrown error in the next line neither.

2021-06-13 15:51 UTC, spielhoelle commented on views/courses.pug
> +          each course, index in courses
We don't need that index

2021-06-13 15:51 UTC, spielhoelle commented on views/courses.pug
> +                  a.text-dark.font-weight-bold(tabindex="0" href="/courses/" + course.slug): +translate("View course")
Tabindex 0 is default so also we don't need this?

2021-06-14 10:31 UTC, Osman190 commented on views/courses.pug
> +                  a.text-dark.font-weight-bold(tabindex="0" href="/courses/" + course.slug): +translate("View course")
but if I removed it it will not work, I tried it

2021-06-14 10:32 UTC, Osman190 commented on controllers/UserController.js
> +        console.log(err)
can we force create user to throw an error? to check it it's really working

2021-06-22 18:32 UTC, Osman190 commented
what is this conflict at views/contactLocations.pug?

2021-06-22 19:19 UTC, closed without merging